### PR TITLE
[wink] Initial work to refactor the binding

### PR DESCRIPTION
**Pull request by shawncrosby**
Hey Sebastian, this isn't ready to merge yet...still needs a few things and some testing, but I wanted to get you something so that you can see what I'm thinking for the refactoring.  I added a new package called org.openhab.binding.wink.client that basically has all the wink api logic in it and then created a new winkbasethinghandler and a new winkhub2bridgehandler to the handler package just to make life easy for a rollback if we don't agree on approach.  I still have to update the thing definition and test it out.

Basically the idea is that you create a wink.cfg in conf/services with the wink client id and secret and refresh token and there is a service that retrieves an access token that is called by the client.  It will refresh automatically if it gets a 401 on one of the gets/puts.  The new thing configuration will simply be the device uuid: Thing DiningRoomLight "Dining Room" {'uuid':'aldkadsjfladskjfla'}

The LockHandler I wrote has been modified to delegate the functioning of the lock to the bridge handler, so basically it just has to define the abstract notion of what the lock is and implement the channel logic.

Have a look through..don't merge it just yet, I'll update when I can.

### CODE REVIEW

**Comment by sebmarchand** [comment]
Hey Shawn,

thanks for working on this! I really like this design and I don't have any objection to it, thank you so much for working on this! As I mentioned on the forum I've bought some Hue light bulbs, which are interesting because they have a lot of "capabilities", we'll need to make sure that we handle this as well (it looks like it'll work but I'll need to confirm this), FYI here's an example of the data that we get for this kind of bulb: https://pastebin.com/Aw6WdxeM   , I'll wait for you to land this refactoring before trying to add support for the "capabilities".

**Comment by shawncrosby** [comment]
OK, cool.  This is really easy to implement.  Desired state is a Map<String,String> and the IWinkClient Interface can be expanded to abstract those away (something like IWinkClient.changeColor(String color){ desired_state.put("color":color); desired_state.put("saturation", saturation); updateDeviceState(device, desired_state);}

**Comment by shawncrosby** [comment]
OK, I got this working, but only for the LockHandler so far.  I'll refactor over the other handlers and do some cleanup and then I'll have to do a little sad path testing on it.

I've changed a bunch of things:

1.  The client id, secret and refresh token have to go into a wink.cfg file in the services folder.  I need to figure out how to deploy a template of the cfg file like I've seen with other plugins, but essentially, you set up the file like:

```
client_id=wink_client_id_alskdjflakjweoiaewi
client_secret=wink_client_secret_alksdjfa;sdjf;a
refresh_token=valid_refresh_token_oaijeaondoaiefo
```

The thing configuration file looks a little different too.  Basically you just define the bridge as a thing and then use the uuid of each thing you want to configure..mine look like this:

```
Bridge   wink:wink_hub_2:hub     "Wink Hub 2"  {
        Thing   wink:lock:FrontDoor     "Lock"          [uuid="3933cf1b-7b29-4a92-80cc-dcefea8d93e7"]
}
```

Then you should be good to go.

I still have to refactor the device discovery service and the other handlers.

**Comment by sebmarchand** [comment]
Thanks for the hard work Shawn, I really like this refactoring!

**Comment by shawncrosby** [comment]
ok Sebastian.  I think this is pretty well good to merge.  I've added a readme to explain how the binding needs to be set up.  I'll leave it to you to merge so that you can review the changes.  Its a pretty significant re-write.

**Comment by sebmarchand** [comment]
Thanks Shawn, this is an awesome refactoring, nice work.

I'm having some issues with this binding (authentication doesn't seem to work) but I'll open an issue with more details about this.

**Pull request merged**
